### ISSUE TITLE
Error reported based on this configuration:Backend failed to start up TypeError

### ISSUE THREAD

**Issue by d-d-up** [immobiliare/backstage-plugin-ldap-auth#483]
[1] Backend failed to start up TypeError: There is no LDAP configuration that matches "ldap://xxx.xxx.xxx:389". Please add a configuration entry for it under "ldap.providers".
[1]     at Function.fromConfig (/Users/forever/web/axx-idp-portal/node_modules/@backstage/plugin-catalog-backend-module-ldap/dist/index.cjs.js:794:13)
[1]     at createPlugin (webpack-internal:///./src/plugins/catalog.ts:17:128)
[1]     at async main (webpack-internal:///./src/index.ts:96:31)

**Comment by antoniomuso** [comment]
This error is relative to the catalog LDAP plugin.^: https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-ldap
