### ISSUE TITLE
Request failed with status 500

### ISSUE THREAD

**Issue by moley** [immobiliare/backstage-plugin-ldap-auth#502]
Hello again, 
I got one step ahead.... 
when using your plugin the binding is finished successfully (without exception), but when searching for the user I recieve: 2023-09-07T20:17:12.091Z backstage error Request failed with status 500 0000202B: RefErr: DSID-0310079C, data 0, 1 access points
[1] 	ref 1: '[THE DN]'
[1]  type=errorHandler lde_message=0000202B: RefErr: DSID-0310079C, data 0, 1 access points
[1] 	ref 1: '[THE DN]'
[1]  lde_dn=null stack=ReferralError: 0000202B: RefErr: DSID-0310079C, data 0, 1 access points
[1] 	ref 1: '[THE DN]'
[1]
[1]     at messageCallback (....node_modules/ldapjs/lib/client/client.js:1220:45)
[1]     at Parser.onMessage (...node_modules/ldapjs/lib/client/client.js:888:14)
[1]     at Parser.emit (node:events:513:28)
[1]     at Parser.write (.../node_modules/ldapjs/lib/messages/parser.js:107:8)
[1]     at TLSSocket.onData (.../node_modules/ldapjs/lib/client/client.js:875:22)
[1]     at TLSSocket.emit (node:events:513:28)
[1]     at addChunk (node:internal/streams/readable:315:12)
[1]     at readableAddChunk (node:internal/streams/readable:289:9)
[1]     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
[1]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

I know this is not a bug of your plugin, but maybe you have a little bit more experience in LDAP handling, so you have an idea and could give me a hint? Would be very nice. 

Thanks in advance
Markus

**Comment by moley** [comment]
Reason was: the userSearchBase was not correct
